"""Condition labels used by conditioned GRPO."""

CORRECT_ANSWER = "<CORRECT_ANSWER>"
PLAUSIBLE_INCORRECT_ANSWER = "<PLAUSIBLE_INCORRECT_ANSWER>"

VALID_CONDITIONS = frozenset({CORRECT_ANSWER, PLAUSIBLE_INCORRECT_ANSWER})
